@echo off

if %1 == 1 (
    echo Training obj %1...
) else if %1 == 2 (
    echo Training obj %1...
    darknet detector train ../data_linemod_gt/02/bvise.data cfg/yolo-linemod-single.cfg darknet53.conv.74 -map
) else if %1 == 3 (
    echo Training obj %1...
) else if %1 == 4 (
    echo Training obj %1...
    darknet detector train ../data_linemod_gt/04/camera.data cfg/yolo-linemod-single.cfg darknet53.conv.74 -map
) else if %1 == 5 (
    echo Training obj %1...
    darknet detector train ../data_linemod_gt/05/can.data cfg/yolo-linemod-single.cfg darknet53.conv.74 -map
) else if %1 == 6 (
    echo Training obj %1...
) else if %1 == 7 (
    echo Training obj %1...
) else if %1 == 8 (
    echo Training obj %1...
) else if %1 == 9 (
    echo Training obj %1...
) else if %1 == 10 (
    echo Training obj %1...
) else if %1 == 11 (
    echo Training obj %1...
) else if %1 == 12 (
    echo Training obj %1...
) else if %1 == 13 (
    echo Training obj %1...
) else if %1 == 14 (
    echo Training obj %1...
) else if %1 == 15 (
    echo Training obj %1...
)